### ISSUE TITLE
deleting messages causes problems in encrypted rooms

### ISSUE THREAD

**Issue by williamkray** [williamkray/maubot-chatgpt#8]
in an encrypted room with threaded-responses disabled, if i delete any message in the recent history the bot has trouble capturing the messages to use for context.

the following is an example from the logs of my testing instance:

```
[06:24:01](file:////opt/maubot/maubot/matrix.py:287)WARNING[client/@clorg:jobmachine.org](https://maubot.dev.jobmachine.org/#/client/@clorg:jobmachine.org)/cryptoget_event: Failed to decrypt $P5iiCx8v3WAsdfeD8tyGrIO-PQPUo3BjKY5yHV5tyv0: Unsupported event content class
[06:24:01](file:////data/plugins/org.jobmachine.chatgpt-v0.0.8-ts1698499308976.mbp/gpt.py:107)ERROR[instance/gpt](https://maubot.dev.jobmachine.org/#/instance/gpt)Something went wrong: Decryption error!
[06:24:01](file:////data/plugins/org.jobmachine.chatgpt-v0.0.8-ts1698499308976.mbp/gpt.py:107)ERROR[instance/gpt](https://maubot.dev.jobmachine.org/#/instance/gpt)Traceback (most recent call last):
  File "/data/plugins/org.jobmachine.chatgpt-v0.0.8-ts1698499308976.mbp/gpt.py", line 91, in on_message
    context = await self.get_context(event)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/plugins/org.jobmachine.chatgpt-v0.0.8-ts1698499308976.mbp/gpt.py", line 176, in get_context
    async for next_event in self.generate_context_messages(event):
  File "/data/plugins/org.jobmachine.chatgpt-v0.0.8-ts1698499308976.mbp/gpt.py", line 216, in generate_context_messages
    raise ValueError("Decryption error!")
ValueError: Decryption error!
```

workarounds include sending a message with enough words in it to push the deletion event far enough back to not be included in the context, or enable threads in the bot temporarily until this naturally happens.

in the meantime, it is strongly advised to avoid deleting messages in encrypted rooms.

**Comment by williamkray** [comment]
i believe this was resolved with some of the recent changes, not sure which commit specifically. but my testing indicates this is no longer an issue. will close, and reopen if needed.
